language: scala
scala:
  - 2.12.3
  - 2.10.6
env:
  - JDK=oraclejdk8
  - JDK=oraclejdk7
before_script:
  - jdk_switcher use $JDK
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - env: SBT_VERSION=1.0.0
    - env: SBT_VERSION=0.13.16
  exclude:
    - scala: 2.12.3
    - env: JDK=oraclejdk7
script: sbt "^^ $SBT_VERSION" clean scripted
